dist: bionic
jdk: openjdk10
language: scala
if: tag IS blank

before_install:
- git fetch --tags
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "push" ]]; then
    openssl aes-256-cbc -K $encrypted_92ba6c816e15_key -iv $encrypted_92ba6c816e15_iv -in private-key.pem.enc -out private-key.pem -d;
    gpg --batch --import private-key.pem;
  fi

stages:
- name: test
- name: release
  if: branch = master AND type = push

jobs:
  include:
  - stage: test
    script: sbt +test
  - stage: release
    script: sbt \"set ThisBuild/version := \"1.1.13\"\" publishSigned sonatypeBundleRelease
    #  - stage: release
    #script: sbt ci-release-sonatype

before_cache:
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local
cache:
  directories:
  - "$HOME/.sbt/1.0/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"
